#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  TARGET="$(readlink "$SOURCE")"
  if [[ $TARGET == /* ]]; then
    SOURCE="$TARGET"
  else
    DIR="$( dirname "$SOURCE" )"
    SOURCE="$DIR/$TARGET"
  fi
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# terminal colors:
# 0 	black
# 1 	red
# 2 	green
# 3 	yellow
# 4 	blue
# 5 	magenta
# 6 	cyan
# 7 	white    
# only colors matching those in bash-prompt available
COLORS=(green yellow blue purple turquoise)
# COLORS=(blue turquoise green yellow orange red pink purple)
ICONS=(fingerprint briefcase dollar cart circle gift vacation fruit pet tree chill)

PROFILE=$1
if [ -z "$PROFILE" ]; then
  echo "Profile not specified, trying current aws-vault profile: $AWS_VAULT"
  PROFILE=$AWS_VAULT
fi

if [ -z "$PROFILE" ]; then
  echo "Please specify the AWS profile to use"
  exit 1
fi

if command -v firefox; then
  FIREFOX=firefox
fi
if [ -f /Applications/Firefox.app/Contents/MacOS/firefox ]; then
  FIREFOX=/Applications/Firefox.app/Contents/MacOS/firefox
fi

COLOR=$(expr $(sum <<< $PROFILE | awk '{print $1}') % ${#COLORS[@]})
ICON=$(expr $(sum <<< $PROFILE | awk '{print $1}') % ${#ICONS[@]})
REGION=$(aws --profile $PROFILE configure get region 2>/dev/null || aws configure get region 2>/dev/null || echo 'eu-west-2')
URL=$(aws-vault login --duration=8h --region=$REGION --stdout "$PROFILE")

if [[ -z "$URL" ]]; then
  echo "Failed to login a session, redirecting to a login page"
  ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
  URL="https://${ACCOUNT_ID}.signin.aws.amazon.com/console"
fi

export FIREFOX
export FIREFOX_ARGS="--new-window"
${SCRIPT_DIR}/firefox-container.sh \
  --name="AWS: ${PROFILE}" \
  --${COLORS[$COLOR]} \
  --${ICONS[$ICON]} \
  $URL
