#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  TARGET="$(readlink "$SOURCE")"
  if [[ $TARGET == /* ]]; then
    SOURCE="$TARGET"
  else
    DIR="$( dirname "$SOURCE" )"
    SOURCE="$DIR/$TARGET"
  fi
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"


COLORS=(blue turquoise green yellow orange red pink purple)
ICONS=(fingerprint briefcase dollar cart circle gift vacation fruit pet tree chill)

PROFILE=$1

COLOR=$(expr $(cksum -a crc <<< $PROFILE | awk '{print $1}') % ${#COLORS[@]})
ICON=$(expr $(cksum -a bsd <<< $PROFILE | awk '{print $1}') % ${#ICONS[@]})

export FIREFOX_ARGS="--new-window"
${SCRIPT_DIR}/firefox-container.sh \
  --name="AWS: ${PROFILE}" \
  --${COLORS[$COLOR]} \
  --${ICONS[$ICON]} \
  $(aws-vault login --duration=8h --region=eu-west-2 --stdout "$1")
